spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${MTWC_G_CLIENT_ID}
            clientSecret: ${MTWC_G_CLIENT_SECRET}
            scope:
              - email
              - profile